---
pst: "on"
watch: "on"
tdir: /home/kusanagi/life/DocumentRoot
odir: _wexal
timezone: Asia/Tokyo
protocol: https
conf:
  editor: vim
  format: yaml
options:
- wp
global_exclude:
- /_wexal
- ~$
- /\.
- /wp-admin
- /wp-includes
- /wp-content/upgrade
- /wp-json/
- /wp-content/plugins
watch_additional_exclude: []
lua:
  fcache:
    enable: 1
    exptime: 60
  header_filter: []
  body_filter: []
worker:
  img:
    "": []
    .webp: []
  css: []
  js: []
wp:
  wexal_init: []
  wexal_head: []
  wexal_enqueue_opt: []
  wexal_footer: []
  wexal_flush:
  - cmd: server push external css
...
