---
pst: "on"
watch: "on"
timezone: Asia/Tokyo
conf:
  editor: vim
  format: yaml
global_exclude:
- ~$
- /\.
- /wp-admin
- /wp-includes
- /wp-content/upgrade
worker:
  img:
    "": []
    .webp: []
  css: []
  js: []
wp:
  wexal_enqueue_opt:
  - cmd: remove emoji
  - cmd: remove css
    args:
    - dashicons
    - vkExUnit_common_style
    - vk-blocks-build-css
    - wp-block-library
    - islemag-fontawesome
    - islemag-fonts
  - cmd: remove css
    args: whats-new-style
    exclude:
      if:
        is_page: mailmag
  - cmd: add css
    args:
    - user-font-awesome
    - /wp-content/plugins/mfo/font-awesome.css
  - cmd: remove js
    args:
    - wp-embed
    - islemag-widget-js
  - cmd: remove js
    args:
    - islemag-owl-carousel
    exclude:
      if: is_front_page
  - cmd: add js
    args:
    - user-lazyload
    - /wp-content/plugins/mfo/jquery.lazyload.min.js
    - - jquery
    - false
    - true
  - cmd: add js
    args:
    - user-sitejs
    - /wp-content/plugins/mfo/site.js
    - - jquery
    - false
    - true
  - cmd: remove hook
    args:
    - wp_head
    - veu_add_smooth_js
  - cmd: remove hook
    args:
    - wp_footer
    - exUnit_print_fbId_script
  - cmd: remove hook
    args:
    - wp_head
    - Closure
    - 10
    - true
  - cmd: remove hook
    args:
    - wp_head
    - - WpSocialBookmarkingLight\Plugin
      - head
    - 10
    - true
    apply:
      if: is_front_page | is_archive | is_page
  - cmd: remove hook
    args:
    - wp_footer
    - - WpSocialBookmarkingLight\Plugin
      - footer
    - 10
    - true
    apply:
      path: ^/$
      if: is_archive | is_page
  wexal_footer: []
  wexal_flush:
  - cmd: shorten url
  - cmd: engagement delay
    args:
      score: 300
      delay: 2500
      ratio: 2
      max-age: 3600
      inline: false
      scripts:
      - name: cl
        type: closure
        pattern: (function(i,s,o,g,r,a,m){
        args: window,document,'script','//www.google-analytics.com/analytics.js','ga'
        cmd:
        - function: ga
          args: "'create', 'UA-6297651-10', 'column.prime-strategy.co.jp'"
        - function: ga
          args: "'send', 'pageview'"
      - name: fa
        type: css
        path: /_wp/mfo/font-awesome.css?ver=5.2.2
  - cmd: server push external css
  - cmd: user lazy load
  - cmd: defer external js
    args:
      apply_script: ""
      exclude_script: ""
...
