---
pst: "on"
watch: "on"
timezone: Asia/Tokyo
global_exclude:
- ~$
- /\.
- /wp-admin
- /wp-includes
- /wp-content/upgrade
- /wp-json/
conf:
  editor: vim
  format: yaml
options:
- lua
- wp
worker:
  img:
    "": []
    .webp: []
    .jp2: []
  css: []
  js: []
lua:
  fcache:
    enbale: 0
    exptime: 60
  header_filter:
  - cmd: wp remove header
  - cmd: set cookie for cdn
    args:
      domain: wexal.jp
#      external_url: https://www.prime-strategy.co.jp/test.js?test=test
  body_filter:
#  - cmd: wp shorten url
  - cmd: wp remove emoji
  - cmd: wp remove meta
#  - cmd: wp remove wpcf7
#    exclude:
#    - /contactus
  - cmd: lazy youtube
    args:
      pc: mq
      mobile: mq
      ratio: "56.25"
wp:
  wexal_init: []
#  - cmd: remove header
  wexal_head:
  - cmd: preload
    args:
#      - /_wt/lightning/inc/font-awesome/versions/5.6.0/webfonts/fa-solid-900.woff2
      - "max-width: 600px": /_wt/lightning/inc/vk-mobile-nav/images/vk-menu-btn-black.svg
  wexal_enqueue_opt:
#  - cmd: remove emoji
#  - cmd: remove meta
  - cmd: engagement delay
  - cmd: remove css
    args:
#    - lightning-theme-style
    - wp-block-library
#    - font-awesome
  - cmd: remove css
    args:
    - ez-icomoon
    - ez-toc
    exclude:
      path: /pst-
  - cmd: remove js
    args:
    - wp-embed
    - bootstrap-js
  - cmd: remove wpcf7
    exclude:
      if:
        is_page: contactus
  wexal_footer:
  wexal_flush:
  - cmd: shorten url
#    exclude:
#      if:
#        is_page: contactus
#  - cmd: lazy youtube
#    args:
#      pc: mq
#      mobile: mq
#      ratio: "56.25"
  - cmd: engagement delay
    exclude:
#     path: ^/$
      if:
        is_page: contactus
#        is_page: contactus
    args:
      score: 180
      pscore: 10
      high: body
      low: load
      delay: 1000
      ratio: 5
#      max-age: 3600
      inline: true
      scripts:
      - name: ga
        type: closure
        pattern: (function(w,d,s,l,i){w[l]=
        args: window,document,'script','dataLayer','GTM-PV5XBLC'
      - name: fa
        type: css
        path: /_wt/lightning/inc/font-awesome/versions/5.6.0/css/all.min.css
        query: auto
      - name: jq
        type: js
        path: /_wi/js/jquery/jquery.js
        query: auto
        sync: sync
      - name: jm
        type: js
        path: /_wi/js/jquery/jquery-migrate.min.js
        query: auto
        sync: sync
      - name: lm
        type: js
        path: /_wt/lightning/assets/js/lightning.min.js
        query: auto
        sync: sync
      - type: js
        path: /_wp/easy-table-of-contents/vendor/smooth-scroll/jquery.smooth-scroll.min.js
      - type: js
        path: /_wp/easy-table-of-contents/vendor/js-cookie/js.cookie.min.js
      - type: js
        path: /_wp/easy-table-of-contents/vendor/sticky-kit/jquery.sticky-kit.min.js
      - type: js
        path: /_wp/easy-table-of-contents/vendor/waypoints/jquery.waypoints.min.js
      - type: js
        path: /_wp/easy-table-of-contents/assets/js/front.min.js
      - name: lz
        type: js
        path: /wp-content/mu-plugins/pst/js/lazy_youtube.js
        query: auto
        sync: async
#  - cmd: defer external js
#    exclude:
#      path: contactus|wp-json
#    args:
#      apply_script: "."
#      exclude_script: ""
  - cmd: server push external css
#  - cmd: set cookie for cdn
#    args:
#      domain: wexal.jp
#      external_url: https://www.prime-strategy.co.jp/test.js
  - cmd: replace
    args:
    - - <link rel="apple-touch-icon-precomposed" href="/_wu/2019/07/cropped-favicon-180x180.png" />
      - ""
      - 1
  - cmd: replace anything
    args:
    - '#<meta name="msapplication-TileImage"[^>]+?>#'
    - ""
    - 1
...
