---
pst: "on"
watch: "on"
timezone: Asia/Tokyo
conf:
  editor: vim
  format: yaml
options:
#- wp
- lua
global_exclude:
- ~$
- /\.
- /wp-admin
- /wp-includes
- /wp-content/upgrade
worker:
  img:
    "": []
    .webp: []
  css: []
  js: []
lua:
  fcache:
    enable: 0
    exptime: 60
  header_filter:
  - cmd: wp remove header
  body_filter:
  - cmd: wp shorten url
  - cmd: engagement delay
    args:
      score: 300
      delay: 2500
      ratio: 2
      max-age: 30
      inline: true
      high: body
      low: load
      scripts:
      - type: css
        path: /_wp/so-widgets-bundle/icons/icomoon/style.css
      - name: cl
        type: closure
        pattern: (function(i,s,o,g,r,a,m){
        args: window,document,'script','//www.google-analytics.com/analytics.js','ga'
        cmd:
        - function: ga
          args: "'create', 'UA-6297651-10', 'column.prime-strategy.co.jp'"
        - function: ga
          args: "'send', 'pageview'"
      - nmae: lp
        type: css
        path: /_wp/latest-posts/assets/css/style.css
      - name: tw
        type: closure
        pattern: '!function(d,s,id){var js,fjs=d'
        args: document, 'script', 'twitter-wjs'
      - name: fb1
        type: closure
        pattern: (function (d, s, id) {
        args: document, 'script', 'facebook-jssdk'
      - name: fb2
        type: closure
        pattern: (function(d, s, id) {
        args: document, 'script', 'facebook-jssdk'
  - cmd: remove link
    args:
    - dashicons
    - vkExUnit_common_style
    - vk-blocks-build-css
    - wp-block-library
    - siteorigin-widget-icon-font-fontawesome-css
    - twitter-feed.css
    - https://fonts.googleapis.com/css?family=Lato:400,700,900
    - /_wp/menu-icons/css/extra.min.css
    - /_wp/so-widgets-bundle/widgets/button/css/style.css
#    - lionmedia-child/style.css
  - cmd: add css
    args:
    - button
    - /_wp/so-widgets-bundle/widgets/button/css/style.css
    - <head>
    - inline
  - cmd: remove link
    args:
    - whats-new.css
    exclude:
    - /mailmag
  - cmd: remove js
    args:
    - wp-embed
    - smooth-scroll
    - viewHelper
    - vk-all-in-one-expansion-unit/assets/js/all.min.js
    - jquery.js
    - jquery-migrate
wp:
  wexal_init: []
  wexal_head: []
  wexal_enqueue_opt: []
  wexal_footer: []
  wexal_flush: []
...
