---
pst: "on"
watch: "on"
timezone: Asia/Tokyo
protocol: https
conf:
  editor: vim
  format: yaml
options:
- lua
#- wp
#- apply_logged_in_user
global_exclude:
- ~$
- /\.
- /wp-admin
- /wp-includes
- /wp-content/upgrade
worker:
  img:
    "": 
    - cmd: auto
      apply: 
      - /test/
      exclude:
      - .png
      args:
        quality: 61.5
        resize: 1920x1080
        jpegtran: ab
    - cmd: auto
      apply: 
      - .
      args:
        quality: 58.5
        resize: 1920x1080
        strip: true
        pngquant: true
        optiping: o4
    .webp: []
    .jp2: []
    .jxr: []
  css: []
  js: []
lua:
  fcache:
    enable: 0
    exptime: 60
  header_filter:
  - cmd: add
    args:
    - 'luajit: test 1'
    - 'luajit: test 2'
    - 'x-luajit: test 3'
  - cmd: replace
    args:
    - 'luajit'
    - 'x-luajit: test 4'
    apply:
    - /category
    exclude:
    - /wordpress
  - cmd: remove
    args:
    - 'link: <https://blog.prime-strategy.co.jp/wp-json/>; rel="https://api.w.org/"'
    - 'x-pingback'
#  - cmd: server push
#    args:
#    - /wp-content/mu-plugins/pst/font/genericons-regular-webfont.ttf
  body_filter:
  - cmd: wp shorten url
#  - cmd: preload
#    args:
#    - /wp-content/mu-plugins/pst/font/genericons-regular-webfont.ttf
  - cmd: remove js
    args:
    - sassy-social-share/public/js/sassy-social-share-public.js
    apply:
    - ^/$|/category/
  - cmd: remove inline js
    args:
    - function heateorSssLoadEvent(e)
    apply:
    - ^/$|/category/
  - cmd: remove inline css
    args:
    - .heateor_sss_horizontal_sharing 
    apply:
    - ^/$|/category/
  - cmd: remove link
    args:
    - sassy-social-share
    - sassy-social-share
    apply:
    - ^/$|/category/
  - cmd: remove link
    args:
    - twentyfourteen-style-css
    - twentyfourteen-lato-css
    - twentyfourteen/css/blocks.css
#    - genericons.css
    - comments/feed
    - feed
    - dns-prefetch
    - dns-prefetch
    - preconnect
    - profile
    - pingback
    - wp-json
    - xmlrpc
    - wlwmanifest
#  - cmd: add css
#    args:
#    - opt-genericons
#    - /wp-content/mu-plugins/pst/css/genericons.css
#    - </body>
#    - false
#  - cmd: add js
#    args:
#    - defer
#    - /wp-content/mu-plugins/pst/js/engagement_delay.js
#    - </body>
#    - true
  - cmd: wp opt genericons
  - cmd: remove js
    args:
    - wp-embed.min.js
  - cmd: remove inline js
    args:
    - 'everything:!0,everythingExceptFlag:!0},i=0;i<j.length;i++)'
  - cmd: remove inline css
    args:
    - img.wp-smiley
  - cmd: remove link
    args:
    - block-library
    - block-library
  - cmd: remove meta
    args:
    - generator
  - cmd: user
  - cmd: replace anything
    args:
    - - 'IF\s+(IE)\s+'
      - 'KUSANAGI Premium Edition $1 7 '
      - 1
      - i
  - cmd: replace
    args:
    - - 'IE 8'
      - '$.\+*?[^]$(){}=!<>|:-$'
      - 1
    - - 'IE 8'
      - 'second'
      - 1
  - cmd: defer external js
    args:
      apply_scirpt: .
      exclude_script: jquery
  - cmd: engagement delay
    apply:
    - ^/$|/category/
    args:
      score: 300
      pscore: 100
      delay: 1000
      ratio: 4
      high: body
      low: load
#      max-age: 60
      inline: true
      scripts:
      - type: css
        path: /wp-content/mu-plugins/pst/css/genericons.css
      - name: jq
        type: js
        path: /_wi/js/jquery/jquery.js
        query: auto
        sync: sync
      - name: jm
        type: js
        path: /_wi/js/jquery/jquery-migrate.min.js
        query: auto
        sync: sync
      - name: fn
        type: js
        path: /_wt/twentyfourteen/js/functions.js
        query: auto
        sync: sync
wp:
  wexal_enqueue_opt:
  - cmd: remove emoji
  - cmd: remove css
    args:
    - twentyfourteen-style
    - twentyfourteen-lato
    - twentyfourteen-ie
    - twentyfourteen-block-style
    - wp-block-library-theme
    - wp-block-library
  - cmd: remove css
    args:
    - heateor_sss_frontend_css
    - heateor_sss_sharing_default_svg
    exclude:
      if: is_singular
  - cmd: remove js
    args:
    - wp-embed
  - cmd: opt genericons
  - cmd: remove js
    args:
    - heateor_sss_sharing_js
  wexal_footer: []
  wexal_flush:
  - cmd: shorten url
  - cmd: server push external css
  - cmd: defer external js
    apply:
      if:
        is_front_page: ""
...
